name: emo_boss
description: EMO Boss

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Adaptive Scrollbar is a library that allows you to create one or more desktop-style scrollbars on a single
  # screen, each of which is bound only to its own object and placed in its own place on the screen.
  adaptive_scrollbar: ^2.1.2
  # A set of cryptographic hashing functions implemented in pure Dart
  crypto: ^3.0.2
  # A cookie manager for http requests in Dart, by which you can deal with the complex cookie policy
  # and persist cookies easily.
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.5
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.3
  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  # Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  dropdown_button2: ^1.9.2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  # A clean and lightweight loading/toast widget for Flutter, Easy to use without context,
  # Support iOSã€Android and Web
  flutter_easyloading: ^3.0.5
  # A CacheManager to download and cache files in the cache directory of the app.
  # Various settings on how long to keep a file can be changed.
  flutter_cache_manager: ^3.3.0
  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
  fl_chart: ^0.55.2
  get: ^4.6.5
  get_it: ^7.2.0
  go_router: ^6.0.1
  html: ^0.15.1
  hive: ^2.2.3
  hive_flutter: 1.1.0
  url_launcher: ^6.1.7
  package_info: ^2.0.2
  path_provider: ^2.0.11
  share: ^2.0.4
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.3.60
  uni_links: ^0.5.1
  custom_pop_up_menu: ^1.2.4
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  retrofit: ^3.3.1
  webcontent_converter: ^0.0.7+2
  jwt_decoder: ^2.0.1
  uuid: ^3.0.7
  flutter_form_builder: ^8.0.0
  form_builder_validators: ^8.4.0
  logger: any
  #  international
  intl: any
  intl_utils: ^2.7.0
  #  list, map, set method
  collection: any
  rxdart: any
  flutter_typeahead: ^4.1.1
  scrollable_positioned_list: ^0.3.5
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  open_file:
    git:
      url: https://github.com/crazecoder/open_file
  # select file
  file_picker: "5.2.1"
  universal_html: ^2.0.8
  flutter_flavor: ^3.1.1
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^3.0.4
  mobile_scanner: ^2.1.0
  kt_dart: any
  qr_flutter: ^4.0.0
  marquee: ^2.2.3
  math_expressions: ^2.3.1
  connectivity_plus: ^3.0.2
  dart_ipify: ^1.1.1
  presentation_displays: ^0.2.3
  image_picker: ^0.8.6
  timezone: ^0.9.1
  flutter_inappwebview: 5.7.2+3
  flutter_dash: 1.0.0
  empty_widget: 0.0.5
  awesome_dialog: 3.0.2
  device_info_plus: 8.1.0
  basic_flutter_theme: ^0.4.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  mocktail: ^0.3.0
  freezed: any
  build_runner: any
  flutter_lints: any
  json_serializable: any
  hive_generator: any
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/html/
    - assets/json/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons/CustomIcons.ttf
flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
  output_dir: lib/common/generated

